version: "3.7"
services:
  api:
    build:
      context: ./
      target: service-email
      network: host
    env_file:
      - .env
    ports:
      - 5950:5950
    restart: always
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    external: true
